### ISSUE TITLE
Azure NTP works differently than Documented

### ISSUE THREAD

**Issue by mrosecrance** [pivotal-cf/docs-ops-manager#114]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/ops-manager/2-9/azure/config-manual.html#director-config
https://docs.pivotal.io/ops-manager/2-10/azure/config-manual.html#director-config

**Is your request for a change or addition to content related to a problem? If so, please describe.**
Azure NTP works differently than the other iaases. We don't allow the user to configure ntp, instead we use a ptp hardware clock. There's a bit more about it [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#check-for-ptp-clock-source) but it's Azure's supposedly less latent and more accurate solution

**Describe the solution you'd like**
The docs aren't misleading about ntp usage.

**Describe alternatives you've considered**
We could revert [this commit](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/f320211548220ccb1efa63f22b59948fbed17b5f) in the stemcell but it seems like moving in the wrong direction.

**Additional context**
Add any other context or screenshots about the content request here.

**Comment by mlimonczenko** [comment]
Hello @mrosecrance ,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
