### ISSUE TITLE
Step 5 Assign Networks, network name is not "management"

### ISSUE THREAD

**Issue by scottbri** [pivotal-cf/docs-ops-manager#13]
when progressing down the PKS installation path, the Assign Networks Network name is actually, "pks-infrastructure-network"

not "management"

**Comment by mjgutermuth** [comment]
Hi @scottbri! Which IaaS docs are you looking at?

**Comment by ograves-pivotal** [comment]
Mr. Brightwell ( @scottbri )
I have researched this issue and found we are already correcting network name inconsistencies within the documentation.  I have confirmed your concerns are being handled as part of that process.  For now I am closing this issue as a 'dupe' of our larger task.

Thank you for your observation and filing this issue!
