### ISSUE TITLE
Ops Manager on Azure Marketplace doesn't exist

### ISSUE THREAD

**Issue by daudna** [pivotal-cf/docs-ops-manager#145]
The Link is not working as "Ops Manager" doesn't exist on Azure Marketplace
https://github.com/pivotal-cf/docs-ops-manager/blob/a729bc496f54aa54e8db5e26a28bd9356bfcef09/install/pcf_azure.html.md.erb#L109

**Comment by qmacro** [comment]
I'm also drawing a blank here - but the fact that this issue is open and uncommented upon for over a year makes me think it's not going to resolved any time soon. 

Is there anyone who can let us know what the situation is here? Thanks.

**Comment by ystros** [comment]
Asking around, it looks like this offering was discontinued last year. I've submitted a PR to remove the page.

The supported way to install Ops Manager / TAS on Azure is documented here: https://docs.pivotal.io/ops-manager/2-10/install/azure.html

**Comment by anita-flegg** [comment]
Looks like this problem was resolved. Closing this issue.
