### ISSUE TITLE
Ops Manager v2.10.15 release notes are missing

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-ops-manager#187]
**URL or GitHub link to the page where you're having the issue**
https://docs.pivotal.io/ops-manager/2-10/release-notes.html
https://github.com/pivotal-cf/docs-ops-manager/blob/2.10/release-notes.html.md.erb#L22

**Is your request for a change or addition to content related to a problem? If so, please describe.**
An addition.  Ops Manager v2.10.15 has been [released on PivNet](https://network.pivotal.io/products/ops-manager/#/releases/914037), but the release notes are missing in the documentation.

**Describe the solution you'd like**
Ops Manager v2.10.15 release notes should be in the documentation.

**Comment by coffee-squirrel** [comment]
Also, I happened to notice the anchor ID for v2.10.14 is `2-10-13` (same as v2.10.13).

https://github.com/pivotal-cf/docs-ops-manager/blob/2.10/release-notes.html.md.erb#L24

**Comment by paigecalvert** [comment]
Thank you! 2.10.15 release notes are live. And good catch on the anchor link, we'll fix it.

**Comment by paigecalvert** [comment]
Actually--looks like that anchor link was already resolved as well. I'll close out this issue, but feel free to log another if you still are seeing these problems!
