### ISSUE TITLE
For GCP, need to configure Excluded Resources in the director tile.

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/docs-ops-manager#3]
I was going to do a PR on this but this section looks to be common, so I am not sure how to proceed. Here is what needs to change.

For GCP, we need to set 169.254.169.254 in the Excluded Resources list. This is because that is the IP of the GCP Metadata (and thereby DNS) resolver. Otherwise you get recursive DNS lookups and have failures to resolve hosts. This is the text I would suggest for GCP:

Current Text:
`(Optional) Enter your list of comma-separated Excluded Recursors to declare which IP addresses and ports should not be used by the DNS server.`

Suggested Text:
`Enter your list of comma-separated Excluded Recursors to declare which IP addresses and ports should not be used by the DNS server, this should minimally include the IP of the Metadata Server (169.254.169.254). Adding this IP is required to avoid name resolution issues with Bosh DNS`

**Comment by pspinrad** [comment]
Hey @matthewfischer -- easy change, I'll do it-- just hafta replace `<%= partial "../common/exclude-recursors" %>` with your suggested text in gcp/config-manual.html.md.erb and gcp/config-terraform.html.md.erb

This applies to all versions of PCF, right?

**Comment by pspinrad** [comment]
Turns out source changes, so did it a different way from ^ https://github.com/pivotal-cf/docs-ops-manager/commit/91082cbd0bd5692ad71dedd586169e1a04b4bcad
