### ISSUE TITLE
PCF 2.5 - S3 Blobstore CA cert configuration instructions

### ISSUE THREAD

**Issue by mdcarlson** [pivotal-cf/docs-ops-manager#35]
I have a question about the instructions at location:

PCF 2.5
URL: https://docs.pivotal.io/pivotalcf/2-5/om/aws/config-terraform.html
- Configuring BOSH Director on AWS Using Terraform
- S3 Compatible Blobstore
- 1 S3 Endpoint 
- c. "Copy the custom public CA certificate..."

The instructions refer to the "public CA certificate you used to sign the S3 endpoint"
The Note box also refers to a "custom CA certificate"

Two questions:
1. What custom CA cert is being referred to in these S3 blobstore instructions and note? 
2. Is "sign the S3 endpoint" correct wording? 

![image](https://user-images.githubusercontent.com/253412/57494588-40832a00-7287-11e9-8f2d-78da9b1e8daa.png)

**Comment by paigecalvert** [comment]
Thanks @mdcarlson! We'll take a look at this
