### ISSUE TITLE
Advanced Meastro Certification Rotation procedure removed from docs

### ISSUE THREAD

**Issue by mrosecrance** [pivotal-cf/docs-ops-manager#351]
**URL or GitHub link to the page where you're having the issue**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

Please remove this page: https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/3.0/vmware-tanzu-ops-manager/security-pcf-infrastructure-advanced-certificate-rotation.html 

Along with any references to it (e.g. It's referrenced here https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/3.0/vmware-tanzu-ops-manager/security-pcf-infrastructure-maestro-tile-compatibility.html and maybe elsewhere). When it makes sense, mention that folks in this situation should contact support.

**Is your request for a change or addition to content related to a problem? If so, please describe.**
A clear and concise description of the problem. For example: "Whenever I upgrade my software I forget to first collect information about the things I've already installed"

Removal of advanced cert rotation instructions since support has raised that customers get into trouble doing this and it would be better to have them contact support.

https://vmware.slack.com/archives/C035LESM2KH/p1707418832292109

**Describe the solution you'd like**
Removal of advanced cert rotation instructions

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or content you've considered.
We could add more warning to the page however I see it called out that it's not recommended already. I believe that much of this information may already exist in support KB's which we could link.

**Additional context**
Add any other context or screenshots about the content request here.

**Comment by anita-flegg** [comment]
@mrosecrance , should I assume this is for both 3.0 and 2.10?

Note to me -- there may also be links from TAS docs.

**Comment by ystros** [comment]
I think a larger discussion is needed here. I do not believe we can outright remove this page from the documentation. Ops Manager's rotation procedure recommendation code will provide links to procedures on this page inside of the Ops Manager product. Removal will break those links.

Many of these procedures are the only way to rotate certain certificates or in certain situations (such as when TKGI is installed alongside other tiles that have certificates; `maestro` is the only way to rotate those certificates). Additionally, the `/services/tls_ca` procedure listed on this page is the de-facto way to rotate that certificate.

**Comment by mrosecrance** [comment]
Closing for now as to Brian's point we need this page still
