### ISSUE TITLE
Custom VM types no longer required for Azure Government

### ISSUE THREAD

**Issue by jgallucci32** [pivotal-cf/docs-ops-manager#4]
According to the documentation, you must set custom VM types for Azure Government (as well as Azure Stack). Based on the suggested script, the VM types are being changed from ones which support Premium disks to ones that only support Standard disks. See documentation for reference:
https://docs.pivotal.io/pivotalcf/2-3/om/azure/config-manual.html#stack-gov-prereqs

Since all of the DS* and F*s VM types are supported in Azure Government, this script is no longer neccessary. In fact, when you go to select "Premium_LRS" from the Director Config page, you will get an error if you set the custom VM types.

**Comment by anita-flegg** [comment]
@cunnie , I just noticed this very old issue, so I checked the docs.
I see that the section this person is talking about is still in the 3.0 docs -- should it be removed?
https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/3.0/vmware-tanzu-ops-manager/azure-config-manual.html

**Comment by ystros** [comment]
@anita-flegg Yes, let's go ahead and remove the Azure Gov specific section. I'd recommend keeping the "Azure Generation 2 VM types" section underneath it; it appears to be unintentionally nested under Azure Gov when in fact it is applicable to all Azure installations.

**Comment by anita-flegg** [comment]
Thanks @ystros. I've made the change in 2.10 and 3.0. 
These will be published and available by Monday afternoon.
