### ISSUE TITLE
Deploying OpsManager OVA and SSH key format

### ISSUE THREAD

**Issue by chipzoller** [pivotal-cf/docs-ops-manager#45]
On the deploy step of the OpsMan OVA, when it comes to the SSH key field as shown [here](https://github.com/pivotal-cf/docs-ops-manager/blob/master/common/images/vsphere/vsphere_om-deploy-07.png), the screenshot implies that only the encoded string is necessary. I have found this to not be true and the entire public key similar to the format required for `authorized_keys` is necessary. For example, the format required is similar to the following:

```ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnZBapWsER/EO1hLYvV/rkZe78mUBueZGHx1kw+ByfNbLoA385Cm72L+6qq40yOIH6R42nHN/bynbeHOD4Ptes4/s2lrLJtTzEWgH9XYnId4sE5f+QTFd2kRtTzZcu8WvFudEIyCIWjO+o9yvPETs05dEl/3KDn+t9uXxiszrG9Ycb2uNNpmDES+ohm9BQQFmpwFnao+UuQbRXLCcQ3SoE3Ai5Z9O+3PBwm0IByx87/dUuqvVISAJ8yGu2hJobx9PPStFERtUsfx5x+WIu9XIkrl5tzxgH9hBDsOS9cVUYJ7kKUUf1yyro6ocHyu6TWHJHSJLt8Z2FULxMPpqdn+8Xw== my-key```

Either an updated screenshot or, preferably, some expounded instruction which explains this would help others in more quickly deploying the OVA.

**Comment by mlimonczenko** [comment]
Hello @chipzoller,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
