### ISSUE TITLE
LB create command - missing path option

### ISSUE THREAD

**Issue by jbinko** [pivotal-cf/docs-ops-manager#47]
Here:
https://github.com/pivotal-cf/docs-ops-manager/blob/2.0/azure/deploy-manual.html.md.erb

This command:
az network lb probe create --lb-name pcf-lb \
--name http8080 --resource-group $RESOURCE_GROUP \
--protocol Http --port 8080

is missing option:
 --path /

without it or another correct path the command is failing

**Comment by mjgutermuth** [comment]
Hello! Apologies for the late followup. Looks like we addressed this issue and forgot to report back. See the updated docs here: https://docs.pivotal.io/ops-manager/2-10/azure/deploy-manual.html#lb
