### ISSUE TITLE
Always pcf-nsg and none opsmgr-nsg?

### ISSUE THREAD

**Issue by jbinko** [pivotal-cf/docs-ops-manager#48]
Here:
https://github.com/pivotal-cf/docs-ops-manager/blob/2.0/azure/deploy-manual.html.md.erb

Those commands:
$ az network vnet subnet create --name Management \
--vnet-name PCF \
--resource-group $RESOURCE_GROUP \
--address-prefix 10.0.4.0/26 \
--network-security-group pcf-nsg
$ az network vnet subnet create --name Deployment \
--vnet-name PCF \
--resource-group $RESOURCE_GROUP \
--address-prefix 10.0.12.0/20 \
--network-security-group pcf-nsg
$ az network vnet subnet create --name Services \
--vnet-name PCF \
--resource-group $RESOURCE_GROUP \
--address-prefix 10.0.8.0/20 \
--network-security-group pcf-nsg

are always referring to the pcf-nsg. I assume one or more of them should refer also to opsmgr-nsg otherwise this opsmgr-nsg is not used and doesn't have to be created.

**Comment by pspinrad** [comment]
Thanks @jbinko -- it looks like you use that `opsmgr-nsg` later, when you create a network interface for Ops Manager, here:
https://github.com/pivotal-cf/docs-ops-manager/blob/2.0/azure/deploy-manual.html.md.erb#L369-L377
Maybe that explains why you need to create an Ops Man NSG?

**Comment by mlimonczenko** [comment]
Hello @jbinko,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
