### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Salamandastron1** [pivotal-cf/docs-ops-manager#55]
This line returns a dead link

https://github.com/pivotal-cf/docs-ops-manager/blob/c5fed96d46ed3ca9945fe95b516ae49e5ee5e352/gcp/config-terraform.html.md.erb#L193

**Comment by mlimonczenko** [comment]
Thank you very much for pointing this out, @Salamandastron1. I pushed a fix (which is located in a different repository) and the changes should reflect shortly.
