### ISSUE TITLE
Docs for configuring BOSH with OM on GCP say to go to BOSH address, not OM address

### ISSUE THREAD

**Issue by amitkgupta** [pivotal-cf/docs-ops-manager#61]
Here: https://github.com/pivotal-cf/docs-ops-manager/blob/2.7/gcp/config-terraform.html.md.erb#L22

Says "In a web browser, navigate to the fully qualified domain name (FQDN) of the BOSH Director."

Should say: "In a web browser, navigate to the fully qualified domain name (FQDN) of the Ops Manager."

**Comment by quixoticmonk** [comment]
Opened the PR (https://github.com/pivotal-cf/docs-ops-manager/pull/65)  to correct this.

**Comment by paigecalvert** [comment]
Thank you @amitkgupta and @quixoticmonk!
