### ISSUE TITLE
Docs to setup BOSH with OM on GCP skip BOSH DNS config

### ISSUE THREAD

**Issue by amitkgupta** [pivotal-cf/docs-ops-manager#62]
Here: https://github.com/pivotal-cf/docs-ops-manager/blob/2.7/gcp/config-terraform.html.md.erb#L205

Goes straight from Security page to Syslog page, but in UI I see there's a BOSH DNS config page for which there's no corresponding walkthrough instruction.

**Comment by mlimonczenko** [comment]
Hello @amitkgupta,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
