### ISSUE TITLE
Services Network Gateway address is incorrect

### ISSUE THREAD

**Issue by fg78nc** [pivotal-cf/docs-ops-manager#67]
Services Network -> Gateway
Enter the first .1 address from the CIDR. For example, if the CIDR is 192.168.16.0/22, enter 192.168.16.1.

Should be (in consistency with infrastructure and runtime networks)
For example, if the CIDR is 192.168.**20**.0/22, enter 192.168.**20**.1.

**Comment by mjgutermuth** [comment]
Thanks! It looks like we addressed this issue and forgot to follow up. See the updated docs here: https://docs.pivotal.io/ops-manager/2-10/gcp/config-manual.html#network
