### ISSUE TITLE
BOSH config on Azuure: Error even if ICMP is enabled

### ISSUE THREAD

**Issue by sudhakarau1** [pivotal-cf/docs-ops-manager#70]
https://github.com/pivotal-cf/docs-ops-manager/blob/2.8/azure/config-terraform.html.md.erb says 
"Click Save. If Enable ICMP checks is not selected, you may see red warnings. You can ignore these warnings.
"
The errors happen even if Enable ICMP checks is enabled:
![image](https://user-images.githubusercontent.com/7424231/76294563-2aab1f00-6307-11ea-87df-acc59e143b69.png)

**Comment by jncd** [comment]
Hello @sudhakarau1 

Thanks for logging this issue. I consulted with the Ops Manager team and learned that if you have selected **Enable ICMP checks**, then you should not ignore the red warnings.

>When Enable ICMP checks is checked, it will block Apply Changes if there's a failure. If it is unchecked, the network verifier will still run but the error can be ignored. In the filed issue, the Ops Manager VM is unable to ping the networks [you] configured.

I hope this helps. I'll adjust the documentation to make this more clear. 

> You might see red warnings. You can ignore them only if Enable ICMP checks is not selected.
