### ISSUE TITLE
Azure Installation Documentation references AWS for Blobstore configuration

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-ops-manager#8]
[Azure Install Documentation](https://docs.pivotal.io/pivotalcf/2-3/om/azure/config-terraform.html#director-config) does not reference to Azure Blobstore, instead it is describing AWS configuration, and the Image is also not reflecting the current Opsmanager configuration options.

**Comment by pspinrad** [comment]
Hey @vchrisb -- it's fine to configure AWS as external blobstore for PCF on Azure (or on any other platform) and for a PCF installation on Azure, I assume internal blobstore means Azure blobstore-- or do you think I'm missing something?
Meanwhile, yes, thanks-- that image is wrong for our Azure install docs and, I now see, all the rest of our v2.3 (and upcoming v2.4) **Director Config** docs-- will update, thanks again for pointing it out.
