### ISSUE TITLE
Docker pull request is failing after updating root CA certificate.

### ISSUE THREAD

**Issue by aneeshbabumk** [pivotal-cf/docs-ops-manager#90]
Docker pull request is failing after updating root CA certificate on PKS clusters. Is there anything to be done after updating root CA certificate

**Comment by mlimonczenko** [comment]
Hello @aneeshbabumk,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
