### ISSUE TITLE
App downtime warning should be in 2.8 and 2.9 version

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-ops-manager#95]
this warning should recommend customers upgrade to operations manager 2.10 to avoid app downtime.  Also we should add this warning to the 2.9 docs. [See Slack thread](https://pivotal.slack.com/archives/C0554UNSS/p1594414814031900)

https://github.com/pivotal-cf/docs-ops-manager/blob/d4f97e84c2933ca0bbf43ddc81db5e752ea274e8/security/pcf-infrastructure/advanced-certificate-rotation.html.md.erb#L10

**Comment by mlimonczenko** [comment]
Thanks, @randomtask1155. I've addressed the issue in the commits above. Definitely feel free to give feedback. 😊

**Comment by randomtask1155** [comment]
commit looks good.  But this warning should also be in the 2.9 docs
