### ISSUE TITLE
How to download terraform templates 

### ISSUE THREAD

**Issue by bzhtux** [pivotal-cf/docs-ops-manager#96]
URL: https://docs.pivotal.io/ops-manager/2-10/gcp/prepare-env-terraform.html but might be true for other cloud providers (not only GCP).

When trying to download terraform templates from VMware Tanzu Network (TAS for VMs), as mentioned, it seems it's no longer available.

I finally downloaded the templates from github: https://github.com/pivotal/paving

So if I'm not wrong, it could help updating the documentation about terraform templates.

**Comment by paigecalvert** [comment]
Thank you @bzhtux!
We are aware of this issue with the docs on terraform templates and plan to address it as soon as possible.
